config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :shoes, only: [:index]
  resources :bottoms, only: [:index]
  resources :tops, only: [:index]
  resources :users
  resources :outfits

  get '/', to: 'users#welcome', as: "welcome"
  get '/login', to: 'sessions#new', as: "login"
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy', as: 'logout'
  get '/myoutfits', to: 'outfits#myoutfits', as: 'myoutfits'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bottom.rb
class Bottom < ApplicationRecord
    has_many :outfits
end

app/models/outfit.rb
class Outfit < ApplicationRecord
    belongs_to :user
    belongs_to :top
    belongs_to :bottom
    belongs_to :shoe

    validates :name, presence: { message: 'Field: You need to call your Outfit something babe.' }
    validates :season, presence: { message: 'Field: Tell me what season you want silly!!' }

    def self.seasons
        ["Spring", "Summer", "Fall", "Winter"]
    end

end

app/models/shoe.rb
class Shoe < ApplicationRecord
    has_many :outfits
end

app/models/top.rb
class Top < ApplicationRecord
    has_many :outfits
end

app/models/user.rb
class User < ApplicationRecord
    has_many :outfits
    has_secure_password

    validates :username, :password, presence: true
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authorized 
    helper_method :current_user

    def current_user
        User.find_by(id: session[:user_id])
    end

    def logged_in?
        !!current_user
    end

    def authorized
        redirect_to login_path unless logged_in?
    end
end

app/controllers/bottoms_controller.rb
class BottomsController < ApplicationController

    def index
        @bottoms = Bottom.all
    end
end

app/controllers/outfits_controller.rb
class OutfitsController < ApplicationController
    before_action :find_outfit, only: [:show, :edit, :update, :destroy]

    def show
        @outfit = Outfit.find(params[:id])
        if  @outfit.user_id == session[:user_id]
            render :show
        else
            redirect_to myoutfits_path
        end
    end

    def new
        @outfit = Outfit.new
        @tops = Top.all
        @bottoms = Bottom.all
        @shoes = Shoe.all
        @seasons = Outfit.seasons
    end

    def create
        @outfit = Outfit.new(outfit_params)
        @outfit.user_id = session[:user_id]
        if @outfit.save
            redirect_to @outfit
        else
            flash[:errors] = @outfit.errors.full_messages
            redirect_to new_outfit_path
        end
    end

    def edit
        @tops = Top.all
        @bottoms = Bottom.all
        @shoes = Shoe.all
        @seasons = Outfit.seasons
    end

    def update
        @outfit.update(outfit_params)
        redirect_to @outfit
    end

    def destroy
        @outfit.destroy
        redirect_to myoutfits_path
    end

    def myoutfits
        @outfits = Outfit.all.select{|outfit| outfit.user_id == session[:user_id]}
    end

    private

    def find_outfit
        @outfit = Outfit.find(params[:id])
    end

    def outfit_params
        params.require(:outfit).permit(:name, :season, :top_id, :bottom_id, :shoe_id)
    end
end 

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    skip_before_action :authorized, only: [:new, :create]

    def new
        
    end

    def create
        @user = User.find_by(username: params[:username])
        if @user && @user.authenticate(params[:password])
            session[:user_id] = @user.id
            redirect_to welcome_path
        else
            flash[:notice] = "Whoops, that didn't work! Try again sweetie <3"
            redirect_to login_path
        end
    end

    def destroy
        session[:user_id] = nil
        redirect_to login_path
    end

end

app/controllers/shoes_controller.rb
class ShoesController < ApplicationController

    def index
        @shoes = Shoe.all
    end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController

    def index
        @tops = Top.all
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    skip_before_action :authorized, only: [:new, :create]

    def new
        @user = User.new
    end

    def create
        @user = User.create(user_params)
        session[:user_id] = @user.id
        if @user.valid?
            redirect_to welcome_path
        else
            flash[:errors] = @user.errors.full_messages
            redirect_to new_user_path
        end
        
    end

    def welcome
        @user = User.find_by(id: session[:user_id])
    end

    private

    def user_params
        params.require(:user).permit(:name, :username, :password)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bottoms_helper.rb
module BottomsHelper
end

app/helpers/outfits_helper.rb
module OutfitsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/shoes_helper.rb
module ShoesHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bottoms/index.html.erb
<h1>Bottoms</h1>

<div class= "row">
    <% @bottoms.each do |bottom| %>
        <div class= "column">
            <div class="card">
                <img class= "standard" src="<%= bottom.image_url%>">
                <%= bottom.brand %> <br>
                <%= bottom.style %> <br>
            </div>
        </div>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <link href="https://fonts.googleapis.com/css?family=News+Cycle&display=swap" rel="stylesheet">
    <title>A&H Outfit App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Oswald&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=PT+Sans+Narrow&display=swap" rel="stylesheet">
  </head>
  <body>
      <div class="app-header">
        <div class="overlay">
          <% if current_user %>
            Logged in as: <%= current_user.name %> 🤩<br>
          <%= link_to "My Outfits", "/myoutfits" %> |       
          <%= link_to "Create an Outfit", "/outfits/new" %> |
          <%= link_to "Tops", "/tops" %> |
          <%= link_to "Bottoms", "/bottoms" %> |
          <%= link_to "Shoes", "/shoes" %> |
          <%= link_to "Log Out", "/logout" %>
          <% end %>
        </div>
      </div>
    <%= yield %>
  </body>
</html>

app/views/outfits/_form.html.erb
<body class="dope_gif">
    <% if flash[:errors] %>
        <% flash[:errors].each do |error| %>
            <%= error %> <br>
        <% end %>
    <% end %>

    <%= form_for @outfit do |f| %>
        <p>Outfit Name: <%= f.text_field :name, :class => "forms" %></p>
        <p>Top: <%= f.collection_select :top_id, @tops, :id, :style, prompt: true %></p>
        <p>Bottom: <%= f.collection_select :bottom_id, @bottoms, :id, :style, prompt: true%></p>
        <p>Shoe: <%= f.collection_select :shoe_id, @shoes, :id, :style, prompt: true%></p>
        <p>Season: <%= f.select :season, @seasons.map {|season| season }, prompt: true %></p>
        <%= f.submit(:class => "buttons")%>
    <% end %>
</body>

app/views/outfits/edit.html.erb
<h1>Edit an Outfit</h1>


<%= render "form" %>

app/views/outfits/index.html.erb
<h1>My Outfits</h1>
<% @outfits.each do |outfit| %>
    Outfit Name: <%= link_to  outfit.name, outfit %><br>
    Top Style: <%= outfit.top.style %><br>
    Bottom Style: <%= outfit.bottom.style %><br>
    Shoe Style: <%= outfit.shoe.style %><br>
<% end %>

app/views/outfits/myoutfits.html.erb
<h1>My Outfits</h1>
<div class= "row">
    <% @outfits.each do |outfit| %>
        <div class= "column">
            <div class="myoutfits_card">
                <h3>Outfit Name: <%= link_to  outfit.name, outfit %><br></h3>
                <img class= "standard" src= "<%= outfit.top.image_url %>">
                <img class= "standard" src= "<%= outfit.bottom.image_url %>">
                <img class= "standard" src= "<%= outfit.shoe.image_url %>"><br>
            </div>
        </div>  
    <% end %>
</div>

app/views/outfits/new.html.erb
<h1>Create an Outfit</h1>


<%= render "form" %>

app/views/outfits/show.html.erb
<h1><%= @outfit.name %></h1>
<div class= "show_row">
    <div class= "column">
        <div class="card">
            <%= @outfit.top.brand %> <br>
            <%= @outfit.top.style %> <br>
            <img class= "standard" src= "<%= @outfit.top.image_url %>"> <br>
        </div>
    </div>
    <div class= "column">
        <div class="card">
            <%= @outfit.bottom.brand %> <br>
            <%= @outfit.bottom.style %> <br>
            <img class= "standard" src= "<%= @outfit.bottom.image_url %>"> <br>
        </div>
    </div>
    <div class= "column">
        <div class="card">
            <%= @outfit.shoe.brand %> <br>
            <%= @outfit.shoe.style %> <br>
            <img class= "standard" src= "<%= @outfit.shoe.image_url %>">
        </div>
    </div>
</div>
<%= button_to("Update Outfit", edit_outfit_path, method: :get, :class => "show_buttons")%> 
<%= button_to("Delete Outfit", @outfit, method: :delete, :class => "show_buttons" )%>  

app/views/shoes/index.html.erb
<h1>Shoes</h1>

<div class= "row">
    <% @shoes.each do |shoe| %>
        <div class= "column">
            <div class="card">
                <img class= "standard" src="<%= shoe.image_url%>">
                <%= shoe.brand %> <br>
                <%= shoe.style %> <br>
            </div>
        </div>
    <% end %>
</div>

app/views/tops/index.html.erb
<h1>Tops</h1>

<div class= "row">
    <% @tops.each do |top| %>
        <div class= "column">
            <div class="card">
                <img class= "standard" src="<%= top.image_url%>">
                <%= top.brand %> <br>
                <%= top.style %> <br>
            </div>
        </div>
    <% end %>
</div>

app/views/users/new.html.erb
<body class="dope_gif">    
    <h1>Sign Up</h1>

    <h4><%= flash[:notice] %></h4>
    <% if flash[:errors] %>
        <% flash[:errors].each do |error| %>
            <h4><%= error %></h4>
        <% end %>
    <% end %>

    <%= form_for @user do |f| %>
        <p>Name: <%= f.text_field :name %></p>
        <p>Username: <%= f.text_field :username %></p>
        <p>Password: <%= f.password_field :password %></p>
    <%= f.submit("Sign Up", :class => "buttons") %>
    <% end %>
    <%= button_to("Login", login_path, method: "get", :class => "buttons") %>
</body>

app/views/users/welcome.html.erb
<body class="dope_gif">
    <h1>Why Hello <%= @user.name %>!! </h1>
</body>